title: Maria Riggs
baseURL: /
params:
  accent_color: pink
  color_scheme: light
  footer:
    content: '&copy; 2019 Unfolding Software. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit by Unfolding Software
        url: 'https://unfoldingsoftware.com'
  header:
    has_nav: true
    logo_img: /images/logo-white-transparent-small.png
    title: Maria Riggs - Make Artistry
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
